language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-18mode
#  - jruby-19mode #TODO fix sqlite dep.
  - rbx-18mode
  - rbx-19mode
#  - ruby-head #breaks on new version of nokogir
#  - jruby-head #
  - 1.8.7
  - ree
notifications:
  email:
    - matt@errplane.com
    - todd@errplane.com
    - paul@errplane.com
  on_success: change
  on_failure: always
script: rake spec:normal