language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-2.3.x
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-2.3.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-3.0.x
    - rvm: jruby-head
      gemfile: gemfiles/Gemfile.rails-3.1.x
notifications:
  email:
    - mechanics@errplane.com
  on_success: change
  on_failure: always
script: rake spec
